import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { SiteShell, PageIntro, Panel, Chip } from "@/components/eoz/SiteShell";
import { ADMIN_NAV, DashNav, StatTile } from "@/components/eoz/DashNav";
import { api, isUnauthenticated, type PageResponse } from "@/lib/api-client";

export const Route = createFileRoute("/admin/notifications")({
  head: () => ({ meta: [{ title: "Notification Queue — EOZ Staff" }] }),
  component: Notifications,
});

type NotificationRow = { id: string; recipientName: string; type: string; title: string; read: boolean; createdAt: string };
type Summary = { total: number; unread: number };

function Notifications() {
  const summaryQuery = useQuery({
    queryKey: ["admin", "notifications", "summary"],
    queryFn: () => api.get<Summary>("/admin/notifications/summary"),
    retry: false,
  });
  const listQuery = useQuery({
    queryKey: ["admin", "notifications", "list"],
    queryFn: () => api.get<PageResponse<NotificationRow>>("/admin/notifications", { size: 30 }),
    retry: false,
  });
  const notifications = listQuery.data?.items ?? [];

  return (
    <SiteShell>
      <PageIntro
        eyebrow="( 06.10 ) — Notifications"
        title="Every message we've sent, visible."
        lead="In-app and best-effort email notifications generated by the platform. SMS and WhatsApp adapters stay disabled until configured."
      />
      <DashNav items={ADMIN_NAV} />

      {isUnauthenticated(summaryQuery.error) ? (
        <Panel className="mb-6">
          <p className="text-sm text-muted">Sign in with a manager or admin account to view the notification feed.</p>
        </Panel>
      ) : null}

      <div className="grid gap-3 pb-6 sm:grid-cols-2 lg:grid-cols-4">
        <StatTile label="Total sent" value={String(summaryQuery.data?.total ?? "—")} />
        <StatTile label="Unread" value={String(summaryQuery.data?.unread ?? "—")} tone="text-amber" />
      </div>
      <Panel className="mb-14">
        <div className="label-mono">Recent notifications</div>
        {notifications.length === 0 ? <p className="mt-4 text-sm text-muted">Nothing sent yet.</p> : null}
        <div className="mt-4 divide-y divide-line">
          {notifications.map((n) => (
            <div key={n.id} className="flex flex-wrap items-center justify-between gap-3 py-3 first:pt-0">
              <div>
                <div className="text-sm">{n.title}</div>
                <div className="text-xs text-muted">
                  {n.recipientName} · {n.type}
                </div>
              </div>
              <div className="flex items-center gap-3">
                <Chip tone={n.read ? "muted" : "amber"}>{n.read ? "Read" : "Unread"}</Chip>
                <span className="text-xs text-muted">{new Date(n.createdAt).toLocaleString()}</span>
              </div>
            </div>
          ))}
        </div>
      </Panel>
    </SiteShell>
  );
}
