-- Seed the service catalogue to match the public site's service pages.
INSERT INTO service_packages (slug, name, description, price, turnaround, active) VALUES
    ('cv-writing', 'Professional CV Writing',
     'A recruiter-ready CV rewritten around your target roles, with clear achievements and ATS-friendly structure.',
     350, '3 working days', TRUE),
    ('cover-letter', 'Tailored Cover Letter',
     'A focused letter written for one specific vacancy, matched to the employer''s stated requirements.',
     180, '2 working days', TRUE),
    ('interview-coaching', 'Interview Coaching',
     'A structured 90-minute mock interview with written feedback on answers, framing and delivery.',
     400, 'Scheduled session', TRUE),
    ('linkedin-profile', 'LinkedIn Profile Optimisation',
     'Headline, About section and experience rewritten so recruiters searching your field actually find you.',
     300, '3 working days', TRUE),
    ('business-profile', 'Company & Business Profile',
     'A polished organisational profile for SMEs bidding for contracts, grants and partnerships.',
     900, '5 working days', TRUE),
    ('recruitment-support', 'Recruitment Support for Employers',
     'Sourcing, screening and shortlisting managed by EOZ for organisations hiring in Zambia.',
     0, 'Agreed per engagement', TRUE),
    ('career-guidance', 'Career Guidance & Application Support',
     'Practical guidance on role targeting, applications and next steps for students, graduates and professionals.',
     250, '60-minute session', TRUE),
    ('marketing-promotion', 'Marketing & Business Promotion',
     'Promote a business, service or opportunity to relevant EOZ audiences through planned content distribution.',
     600, 'Agreed per campaign', TRUE),
    ('skills-training', 'Capacity Building & Skills Training',
     'Practical workshops and training programmes that build employability, workplace and business capability.',
     1500, 'Agreed per programme', TRUE);
