/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CookieNoticeRouteImport } from './routes/cookie-notice'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScamWarningRouteImport } from './routes/scam-warning'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOpportunitiesRouteImport } from './routes/admin.opportunities'
import { Route as AdminOrganisationsRouteImport } from './routes/admin.organisations'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminRecruitmentRouteImport } from './routes/admin.recruitment'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CandidateIndexRouteImport } from './routes/candidate.index'
import { Route as CandidateAccountRouteImport } from './routes/candidate.account'
import { Route as CandidateAlertsRouteImport } from './routes/candidate.alerts'
import { Route as CandidateApplicationsRouteImport } from './routes/candidate.applications'
import { Route as CandidateDocumentsRouteImport } from './routes/candidate.documents'
import { Route as CandidateMessagesRouteImport } from './routes/candidate.messages'
import { Route as CandidateNotificationsRouteImport } from './routes/candidate.notifications'
import { Route as CandidateOrdersRouteImport } from './routes/candidate.orders'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateSavedRouteImport } from './routes/candidate.saved'
import { Route as EmployersIndexRouteImport } from './routes/employers.index'
import { Route as EmployersAnalyticsRouteImport } from './routes/employers.analytics'
import { Route as EmployersApplicantsRouteImport } from './routes/employers.applicants'
import { Route as EmployersDashboardRouteImport } from './routes/employers.dashboard'
import { Route as EmployersFinanceRouteImport } from './routes/employers.finance'
import { Route as EmployersListingsRouteImport } from './routes/employers.listings'
import { Route as EmployersOrganisationRouteImport } from './routes/employers.organisation'
import { Route as EmployersPostRouteImport } from './routes/employers.post'
import { Route as EmployersPricingRouteImport } from './routes/employers.pricing'
import { Route as EmployersRecruitmentRouteImport } from './routes/employers.recruitment'
import { Route as EmployersServicesRouteImport } from './routes/employers.services'
import { Route as EmployersTeamRouteImport } from './routes/employers.team'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as OpportunitiesOpportunityIdRouteImport } from './routes/opportunities.$opportunityId'
import { Route as OrganisationsIndexRouteImport } from './routes/organisations.index'
import { Route as OrganisationsOrganisationIdRouteImport } from './routes/organisations.$organisationId'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesServiceSlugRouteImport } from './routes/services.$serviceSlug'
import { Route as AdminRecruitmentProjectIdRouteImport } from './routes/admin.recruitment.$projectId'
import { Route as AdminRecruitmentTalentPoolRouteImport } from './routes/admin.recruitment.talent-pool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieNoticeRoute = CookieNoticeRouteImport.update({
  id: '/cookie-notice',
  path: '/cookie-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamWarningRoute = ScamWarningRouteImport.update({
  id: '/scam-warning',
  path: '/scam-warning',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/admin/health',
  path: '/admin/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpportunitiesRoute = AdminOpportunitiesRouteImport.update({
  id: '/admin/opportunities',
  path: '/admin/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganisationsRoute = AdminOrganisationsRouteImport.update({
  id: '/admin/organisations',
  path: '/admin/organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecruitmentRoute = AdminRecruitmentRouteImport.update({
  id: '/admin/recruitment',
  path: '/admin/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateAccountRoute = CandidateAccountRouteImport.update({
  id: '/candidate/account',
  path: '/candidate/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateAlertsRoute = CandidateAlertsRouteImport.update({
  id: '/candidate/alerts',
  path: '/candidate/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateApplicationsRoute = CandidateApplicationsRouteImport.update({
  id: '/candidate/applications',
  path: '/candidate/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDocumentsRoute = CandidateDocumentsRouteImport.update({
  id: '/candidate/documents',
  path: '/candidate/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateMessagesRoute = CandidateMessagesRouteImport.update({
  id: '/candidate/messages',
  path: '/candidate/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateNotificationsRoute = CandidateNotificationsRouteImport.update({
  id: '/candidate/notifications',
  path: '/candidate/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateOrdersRoute = CandidateOrdersRouteImport.update({
  id: '/candidate/orders',
  path: '/candidate/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateSavedRoute = CandidateSavedRouteImport.update({
  id: '/candidate/saved',
  path: '/candidate/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersIndexRoute = EmployersIndexRouteImport.update({
  id: '/employers/',
  path: '/employers/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersAnalyticsRoute = EmployersAnalyticsRouteImport.update({
  id: '/employers/analytics',
  path: '/employers/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersApplicantsRoute = EmployersApplicantsRouteImport.update({
  id: '/employers/applicants',
  path: '/employers/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersDashboardRoute = EmployersDashboardRouteImport.update({
  id: '/employers/dashboard',
  path: '/employers/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersFinanceRoute = EmployersFinanceRouteImport.update({
  id: '/employers/finance',
  path: '/employers/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersListingsRoute = EmployersListingsRouteImport.update({
  id: '/employers/listings',
  path: '/employers/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersOrganisationRoute = EmployersOrganisationRouteImport.update({
  id: '/employers/organisation',
  path: '/employers/organisation',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersPostRoute = EmployersPostRouteImport.update({
  id: '/employers/post',
  path: '/employers/post',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersPricingRoute = EmployersPricingRouteImport.update({
  id: '/employers/pricing',
  path: '/employers/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRecruitmentRoute = EmployersRecruitmentRouteImport.update({
  id: '/employers/recruitment',
  path: '/employers/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersServicesRoute = EmployersServicesRouteImport.update({
  id: '/employers/services',
  path: '/employers/services',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersTeamRoute = EmployersTeamRouteImport.update({
  id: '/employers/team',
  path: '/employers/team',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesOpportunityIdRoute =
  OpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganisationsIndexRoute = OrganisationsIndexRouteImport.update({
  id: '/organisations/',
  path: '/organisations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsOrganisationIdRoute =
  OrganisationsOrganisationIdRouteImport.update({
    id: '/organisations/$organisationId',
    path: '/organisations/$organisationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceSlugRoute = ServicesServiceSlugRouteImport.update({
  id: '/services/$serviceSlug',
  path: '/services/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecruitmentProjectIdRoute =
  AdminRecruitmentProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AdminRecruitmentRoute,
  } as any)
const AdminRecruitmentTalentPoolRoute =
  AdminRecruitmentTalentPoolRouteImport.update({
    id: '/talent-pool',
    path: '/talent-pool',
    getParentRoute: () => AdminRecruitmentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/cookie-notice': typeof CookieNoticeRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scam-warning': typeof ScamWarningRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/organisations': typeof AdminOrganisationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/recruitment': typeof AdminRecruitmentRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/account': typeof CandidateAccountRoute
  '/candidate/alerts': typeof CandidateAlertsRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/documents': typeof CandidateDocumentsRoute
  '/candidate/messages': typeof CandidateMessagesRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/orders': typeof CandidateOrdersRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/saved': typeof CandidateSavedRoute
  '/employers/analytics': typeof EmployersAnalyticsRoute
  '/employers/applicants': typeof EmployersApplicantsRoute
  '/employers/dashboard': typeof EmployersDashboardRoute
  '/employers/finance': typeof EmployersFinanceRoute
  '/employers/listings': typeof EmployersListingsRoute
  '/employers/organisation': typeof EmployersOrganisationRoute
  '/employers/post': typeof EmployersPostRoute
  '/employers/pricing': typeof EmployersPricingRoute
  '/employers/recruitment': typeof EmployersRecruitmentRoute
  '/employers/services': typeof EmployersServicesRoute
  '/employers/team': typeof EmployersTeamRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/organisations/$organisationId': typeof OrganisationsOrganisationIdRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/employers/': typeof EmployersIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/organisations/': typeof OrganisationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/recruitment/$projectId': typeof AdminRecruitmentProjectIdRoute
  '/admin/recruitment/talent-pool': typeof AdminRecruitmentTalentPoolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/cookie-notice': typeof CookieNoticeRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scam-warning': typeof ScamWarningRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/organisations': typeof AdminOrganisationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/recruitment': typeof AdminRecruitmentRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/account': typeof CandidateAccountRoute
  '/candidate/alerts': typeof CandidateAlertsRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/documents': typeof CandidateDocumentsRoute
  '/candidate/messages': typeof CandidateMessagesRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/orders': typeof CandidateOrdersRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/saved': typeof CandidateSavedRoute
  '/employers/analytics': typeof EmployersAnalyticsRoute
  '/employers/applicants': typeof EmployersApplicantsRoute
  '/employers/dashboard': typeof EmployersDashboardRoute
  '/employers/finance': typeof EmployersFinanceRoute
  '/employers/listings': typeof EmployersListingsRoute
  '/employers/organisation': typeof EmployersOrganisationRoute
  '/employers/post': typeof EmployersPostRoute
  '/employers/pricing': typeof EmployersPricingRoute
  '/employers/recruitment': typeof EmployersRecruitmentRoute
  '/employers/services': typeof EmployersServicesRoute
  '/employers/team': typeof EmployersTeamRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/organisations/$organisationId': typeof OrganisationsOrganisationIdRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/admin': typeof AdminIndexRoute
  '/candidate': typeof CandidateIndexRoute
  '/employers': typeof EmployersIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/organisations': typeof OrganisationsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/recruitment/$projectId': typeof AdminRecruitmentProjectIdRoute
  '/admin/recruitment/talent-pool': typeof AdminRecruitmentTalentPoolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/cookie-notice': typeof CookieNoticeRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scam-warning': typeof ScamWarningRoute
  '/terms': typeof TermsRoute
  '/verification': typeof VerificationRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/opportunities': typeof AdminOpportunitiesRoute
  '/admin/organisations': typeof AdminOrganisationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/recruitment': typeof AdminRecruitmentRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/candidate/account': typeof CandidateAccountRoute
  '/candidate/alerts': typeof CandidateAlertsRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/documents': typeof CandidateDocumentsRoute
  '/candidate/messages': typeof CandidateMessagesRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/orders': typeof CandidateOrdersRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/saved': typeof CandidateSavedRoute
  '/employers/analytics': typeof EmployersAnalyticsRoute
  '/employers/applicants': typeof EmployersApplicantsRoute
  '/employers/dashboard': typeof EmployersDashboardRoute
  '/employers/finance': typeof EmployersFinanceRoute
  '/employers/listings': typeof EmployersListingsRoute
  '/employers/organisation': typeof EmployersOrganisationRoute
  '/employers/post': typeof EmployersPostRoute
  '/employers/pricing': typeof EmployersPricingRoute
  '/employers/recruitment': typeof EmployersRecruitmentRoute
  '/employers/services': typeof EmployersServicesRoute
  '/employers/team': typeof EmployersTeamRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/organisations/$organisationId': typeof OrganisationsOrganisationIdRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/employers/': typeof EmployersIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/organisations/': typeof OrganisationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/recruitment/$projectId': typeof AdminRecruitmentProjectIdRoute
  '/admin/recruitment/talent-pool': typeof AdminRecruitmentTalentPoolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/auth'
    | '/candidates'
    | '/contact'
    | '/content'
    | '/cookie-notice'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/partners'
    | '/privacy'
    | '/report'
    | '/reset-password'
    | '/scam-warning'
    | '/terms'
    | '/verification'
    | '/verify-email'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/finance'
    | '/admin/health'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/opportunities'
    | '/admin/organisations'
    | '/admin/permissions'
    | '/admin/recruitment'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/candidate/account'
    | '/candidate/alerts'
    | '/candidate/applications'
    | '/candidate/documents'
    | '/candidate/messages'
    | '/candidate/notifications'
    | '/candidate/orders'
    | '/candidate/profile'
    | '/candidate/saved'
    | '/employers/analytics'
    | '/employers/applicants'
    | '/employers/dashboard'
    | '/employers/finance'
    | '/employers/listings'
    | '/employers/organisation'
    | '/employers/post'
    | '/employers/pricing'
    | '/employers/recruitment'
    | '/employers/services'
    | '/employers/team'
    | '/opportunities/$opportunityId'
    | '/organisations/$organisationId'
    | '/services/$serviceSlug'
    | '/admin/'
    | '/candidate/'
    | '/employers/'
    | '/opportunities/'
    | '/organisations/'
    | '/services/'
    | '/admin/recruitment/$projectId'
    | '/admin/recruitment/talent-pool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/auth'
    | '/candidates'
    | '/contact'
    | '/content'
    | '/cookie-notice'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/partners'
    | '/privacy'
    | '/report'
    | '/reset-password'
    | '/scam-warning'
    | '/terms'
    | '/verification'
    | '/verify-email'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/finance'
    | '/admin/health'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/opportunities'
    | '/admin/organisations'
    | '/admin/permissions'
    | '/admin/recruitment'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/candidate/account'
    | '/candidate/alerts'
    | '/candidate/applications'
    | '/candidate/documents'
    | '/candidate/messages'
    | '/candidate/notifications'
    | '/candidate/orders'
    | '/candidate/profile'
    | '/candidate/saved'
    | '/employers/analytics'
    | '/employers/applicants'
    | '/employers/dashboard'
    | '/employers/finance'
    | '/employers/listings'
    | '/employers/organisation'
    | '/employers/post'
    | '/employers/pricing'
    | '/employers/recruitment'
    | '/employers/services'
    | '/employers/team'
    | '/opportunities/$opportunityId'
    | '/organisations/$organisationId'
    | '/services/$serviceSlug'
    | '/admin'
    | '/candidate'
    | '/employers'
    | '/opportunities'
    | '/organisations'
    | '/services'
    | '/admin/recruitment/$projectId'
    | '/admin/recruitment/talent-pool'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/auth'
    | '/candidates'
    | '/contact'
    | '/content'
    | '/cookie-notice'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/partners'
    | '/privacy'
    | '/report'
    | '/reset-password'
    | '/scam-warning'
    | '/terms'
    | '/verification'
    | '/verify-email'
    | '/admin/audit'
    | '/admin/content'
    | '/admin/finance'
    | '/admin/health'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/opportunities'
    | '/admin/organisations'
    | '/admin/permissions'
    | '/admin/recruitment'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/candidate/account'
    | '/candidate/alerts'
    | '/candidate/applications'
    | '/candidate/documents'
    | '/candidate/messages'
    | '/candidate/notifications'
    | '/candidate/orders'
    | '/candidate/profile'
    | '/candidate/saved'
    | '/employers/analytics'
    | '/employers/applicants'
    | '/employers/dashboard'
    | '/employers/finance'
    | '/employers/listings'
    | '/employers/organisation'
    | '/employers/post'
    | '/employers/pricing'
    | '/employers/recruitment'
    | '/employers/services'
    | '/employers/team'
    | '/opportunities/$opportunityId'
    | '/organisations/$organisationId'
    | '/services/$serviceSlug'
    | '/admin/'
    | '/candidate/'
    | '/employers/'
    | '/opportunities/'
    | '/organisations/'
    | '/services/'
    | '/admin/recruitment/$projectId'
    | '/admin/recruitment/talent-pool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CandidatesRoute: typeof CandidatesRoute
  ContactRoute: typeof ContactRoute
  ContentRoute: typeof ContentRoute
  CookieNoticeRoute: typeof CookieNoticeRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScamWarningRoute: typeof ScamWarningRoute
  TermsRoute: typeof TermsRoute
  VerificationRoute: typeof VerificationRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOpportunitiesRoute: typeof AdminOpportunitiesRoute
  AdminOrganisationsRoute: typeof AdminOrganisationsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminRecruitmentRoute: typeof AdminRecruitmentRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CandidateAccountRoute: typeof CandidateAccountRoute
  CandidateAlertsRoute: typeof CandidateAlertsRoute
  CandidateApplicationsRoute: typeof CandidateApplicationsRoute
  CandidateDocumentsRoute: typeof CandidateDocumentsRoute
  CandidateMessagesRoute: typeof CandidateMessagesRoute
  CandidateNotificationsRoute: typeof CandidateNotificationsRoute
  CandidateOrdersRoute: typeof CandidateOrdersRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateSavedRoute: typeof CandidateSavedRoute
  EmployersAnalyticsRoute: typeof EmployersAnalyticsRoute
  EmployersApplicantsRoute: typeof EmployersApplicantsRoute
  EmployersDashboardRoute: typeof EmployersDashboardRoute
  EmployersFinanceRoute: typeof EmployersFinanceRoute
  EmployersListingsRoute: typeof EmployersListingsRoute
  EmployersOrganisationRoute: typeof EmployersOrganisationRoute
  EmployersPostRoute: typeof EmployersPostRoute
  EmployersPricingRoute: typeof EmployersPricingRoute
  EmployersRecruitmentRoute: typeof EmployersRecruitmentRoute
  EmployersServicesRoute: typeof EmployersServicesRoute
  EmployersTeamRoute: typeof EmployersTeamRoute
  OpportunitiesOpportunityIdRoute: typeof OpportunitiesOpportunityIdRoute
  OrganisationsOrganisationIdRoute: typeof OrganisationsOrganisationIdRoute
  ServicesServiceSlugRoute: typeof ServicesServiceSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  EmployersIndexRoute: typeof EmployersIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  OrganisationsIndexRoute: typeof OrganisationsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-notice': {
      id: '/cookie-notice'
      path: '/cookie-notice'
      fullPath: '/cookie-notice'
      preLoaderRoute: typeof CookieNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scam-warning': {
      id: '/scam-warning'
      path: '/scam-warning'
      fullPath: '/scam-warning'
      preLoaderRoute: typeof ScamWarningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/admin/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities': {
      id: '/admin/opportunities'
      path: '/admin/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AdminOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organisations': {
      id: '/admin/organisations'
      path: '/admin/organisations'
      fullPath: '/admin/organisations'
      preLoaderRoute: typeof AdminOrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recruitment': {
      id: '/admin/recruitment'
      path: '/admin/recruitment'
      fullPath: '/admin/recruitment'
      preLoaderRoute: typeof AdminRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/account': {
      id: '/candidate/account'
      path: '/candidate/account'
      fullPath: '/candidate/account'
      preLoaderRoute: typeof CandidateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/alerts': {
      id: '/candidate/alerts'
      path: '/candidate/alerts'
      fullPath: '/candidate/alerts'
      preLoaderRoute: typeof CandidateAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/applications': {
      id: '/candidate/applications'
      path: '/candidate/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof CandidateApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/documents': {
      id: '/candidate/documents'
      path: '/candidate/documents'
      fullPath: '/candidate/documents'
      preLoaderRoute: typeof CandidateDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/messages': {
      id: '/candidate/messages'
      path: '/candidate/messages'
      fullPath: '/candidate/messages'
      preLoaderRoute: typeof CandidateMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/notifications': {
      id: '/candidate/notifications'
      path: '/candidate/notifications'
      fullPath: '/candidate/notifications'
      preLoaderRoute: typeof CandidateNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/orders': {
      id: '/candidate/orders'
      path: '/candidate/orders'
      fullPath: '/candidate/orders'
      preLoaderRoute: typeof CandidateOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/saved': {
      id: '/candidate/saved'
      path: '/candidate/saved'
      fullPath: '/candidate/saved'
      preLoaderRoute: typeof CandidateSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/': {
      id: '/employers/'
      path: '/employers'
      fullPath: '/employers/'
      preLoaderRoute: typeof EmployersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/analytics': {
      id: '/employers/analytics'
      path: '/employers/analytics'
      fullPath: '/employers/analytics'
      preLoaderRoute: typeof EmployersAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/applicants': {
      id: '/employers/applicants'
      path: '/employers/applicants'
      fullPath: '/employers/applicants'
      preLoaderRoute: typeof EmployersApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/dashboard': {
      id: '/employers/dashboard'
      path: '/employers/dashboard'
      fullPath: '/employers/dashboard'
      preLoaderRoute: typeof EmployersDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/finance': {
      id: '/employers/finance'
      path: '/employers/finance'
      fullPath: '/employers/finance'
      preLoaderRoute: typeof EmployersFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/listings': {
      id: '/employers/listings'
      path: '/employers/listings'
      fullPath: '/employers/listings'
      preLoaderRoute: typeof EmployersListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/organisation': {
      id: '/employers/organisation'
      path: '/employers/organisation'
      fullPath: '/employers/organisation'
      preLoaderRoute: typeof EmployersOrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/post': {
      id: '/employers/post'
      path: '/employers/post'
      fullPath: '/employers/post'
      preLoaderRoute: typeof EmployersPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/pricing': {
      id: '/employers/pricing'
      path: '/employers/pricing'
      fullPath: '/employers/pricing'
      preLoaderRoute: typeof EmployersPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/recruitment': {
      id: '/employers/recruitment'
      path: '/employers/recruitment'
      fullPath: '/employers/recruitment'
      preLoaderRoute: typeof EmployersRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/services': {
      id: '/employers/services'
      path: '/employers/services'
      fullPath: '/employers/services'
      preLoaderRoute: typeof EmployersServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/team': {
      id: '/employers/team'
      path: '/employers/team'
      fullPath: '/employers/team'
      preLoaderRoute: typeof EmployersTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$opportunityId': {
      id: '/opportunities/$opportunityId'
      path: '/opportunities/$opportunityId'
      fullPath: '/opportunities/$opportunityId'
      preLoaderRoute: typeof OpportunitiesOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/': {
      id: '/organisations/'
      path: '/organisations'
      fullPath: '/organisations/'
      preLoaderRoute: typeof OrganisationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/$organisationId': {
      id: '/organisations/$organisationId'
      path: '/organisations/$organisationId'
      fullPath: '/organisations/$organisationId'
      preLoaderRoute: typeof OrganisationsOrganisationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceSlug': {
      id: '/services/$serviceSlug'
      path: '/services/$serviceSlug'
      fullPath: '/services/$serviceSlug'
      preLoaderRoute: typeof ServicesServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recruitment/$projectId': {
      id: '/admin/recruitment/$projectId'
      path: '/$projectId'
      fullPath: '/admin/recruitment/$projectId'
      preLoaderRoute: typeof AdminRecruitmentProjectIdRouteImport
      parentRoute: typeof AdminRecruitmentRoute
    }
    '/admin/recruitment/talent-pool': {
      id: '/admin/recruitment/talent-pool'
      path: '/talent-pool'
      fullPath: '/admin/recruitment/talent-pool'
      preLoaderRoute: typeof AdminRecruitmentTalentPoolRouteImport
      parentRoute: typeof AdminRecruitmentRoute
    }
  }
}

interface AdminRecruitmentRouteChildren {
  AdminRecruitmentProjectIdRoute: typeof AdminRecruitmentProjectIdRoute
  AdminRecruitmentTalentPoolRoute: typeof AdminRecruitmentTalentPoolRoute
}

const AdminRecruitmentRouteChildren: AdminRecruitmentRouteChildren = {
  AdminRecruitmentProjectIdRoute: AdminRecruitmentProjectIdRoute,
  AdminRecruitmentTalentPoolRoute: AdminRecruitmentTalentPoolRoute,
}

const AdminRecruitmentRouteWithChildren =
  AdminRecruitmentRoute._addFileChildren(AdminRecruitmentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CandidatesRoute: CandidatesRoute,
  ContactRoute: ContactRoute,
  ContentRoute: ContentRoute,
  CookieNoticeRoute: CookieNoticeRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScamWarningRoute: ScamWarningRoute,
  TermsRoute: TermsRoute,
  VerificationRoute: VerificationRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminContentRoute: AdminContentRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOpportunitiesRoute: AdminOpportunitiesRoute,
  AdminOrganisationsRoute: AdminOrganisationsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminRecruitmentRoute: AdminRecruitmentRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CandidateAccountRoute: CandidateAccountRoute,
  CandidateAlertsRoute: CandidateAlertsRoute,
  CandidateApplicationsRoute: CandidateApplicationsRoute,
  CandidateDocumentsRoute: CandidateDocumentsRoute,
  CandidateMessagesRoute: CandidateMessagesRoute,
  CandidateNotificationsRoute: CandidateNotificationsRoute,
  CandidateOrdersRoute: CandidateOrdersRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateSavedRoute: CandidateSavedRoute,
  EmployersAnalyticsRoute: EmployersAnalyticsRoute,
  EmployersApplicantsRoute: EmployersApplicantsRoute,
  EmployersDashboardRoute: EmployersDashboardRoute,
  EmployersFinanceRoute: EmployersFinanceRoute,
  EmployersListingsRoute: EmployersListingsRoute,
  EmployersOrganisationRoute: EmployersOrganisationRoute,
  EmployersPostRoute: EmployersPostRoute,
  EmployersPricingRoute: EmployersPricingRoute,
  EmployersRecruitmentRoute: EmployersRecruitmentRoute,
  EmployersServicesRoute: EmployersServicesRoute,
  EmployersTeamRoute: EmployersTeamRoute,
  OpportunitiesOpportunityIdRoute: OpportunitiesOpportunityIdRoute,
  OrganisationsOrganisationIdRoute: OrganisationsOrganisationIdRoute,
  ServicesServiceSlugRoute: ServicesServiceSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  EmployersIndexRoute: EmployersIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  OrganisationsIndexRoute: OrganisationsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
